import { Montserrat } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Offline from "@/components/reusables/offline";
import Toast from "@/components/reusables/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const MainFont = Montserrat({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${MainFont.className}`}>
        <>{children}</>
        <Offline />
        <Toast />
      </body>
    </html>
  );
}
